version: 2
jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - checkout

      - run:
          name: "Install dependencies"
          command: |
            pip3 install python-dateutil

      - run:
          name: "Run Tests"
          command: |
            pip3 install --user behave && ln -s $HOME/.local/bin/behave $BINDIR
            mkdir -p /tmp/artifacts
            behave --junit --junit-directory /tmp/artifacts tests/features

      - store_artifacts:
          path: /tmp/artifacts

      - store_test_results:
          path: /tmp/artifacts
