name: Run basic acceptance testing
on: [push]
env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Run Behave tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        cache: 'pipenv'
        python-version: "3.10"
    - name: Install pipenv
      run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
    - run: make test
Skip to content

Search or jump to...

Pulls

Issues

Codespaces

Marketplace

Explore

 

@mowjoejoejoejoe 

mowjoejoejoejoe

/

archive-repo

Public

forked from MikeBishop/archive-repo

Fork your own copy of mowjoejoejoejoe/archive-repo

Code

Pull requests

Actions

Projects

Wiki

Security

Insights

Settings

mowjoejoejoejoe/archive-repo

This branch is 1 commit ahead of MikeBishop:main.

Latest commit

@mowjoejoejoejoe

mowjoejoejoejoe Update pyproject.toml

…

3 minutes ago

Git stats

 25

Files

Type

Name

Latest commit message

Commit time

.github/workflows

Add initial test invocation to GHA

last month

archive-repo

Ensure shared is included

2 years ago

post-processing/viewer

Focus issues when they show

2 years ago

tests

Use published version for known-good

2 years ago

.gitignore

Test infrastructure

3 years ago

LICENSE

Documentation and help

2 years ago

Makefile

Build setup

2 weeks ago

Pipfile

Switch to pipenv

last month

Pipfile.lock

Switch to pipenv

last month

README.md

Documentation and help

2 years ago

pyproject.toml

Update pyproject.toml

3 minutes ago

setup.py

Build setup

2 weeks ago

README.md

archive-repo

Captures and stores data about a GitHub repo for archival purposes

Archive command

usage: python3 -m archive-repo archive [-h] [--reference [REFFILE]] [--issues-only] [--quiet] repo githubToken [outFile]

Archive repo issues and PRs.

positional arguments:

repo: The GitHub repository to fetch, e.g. "quicwg/base-drafts"

githubToken: A token for a GitHub account with permission to read the selected repository; see https://github.com/settings/tokens

outfile: Where the output should be written; if omitted, stdout is used.

optional arguments:

-h: Displays help text

--reference: Optionally, previous output of this script. Makes the new run faster, since only new/changed issues and PRs need to be fetched.

--issues-only: Only fetch issues, not PRs

--quiet: Only write errors to stderr; otherwise, status is written to stderr

Note that providing an output file can make processing faster if the respository has not changed since the reference file was generated.

Generate PR Branches

usage: python3 -m archive-repo pr_branches [-h] [--include-merged] [--dry-run] input repo git_dir

Identify the source repos and forks of PRs from an archive, creating local branches as needed

positional arguments:

input: Archive file generated by python3 -m archive-repo archive

repo: Target GitHub repo

git_dir: Local directory with git repo (default: local directory)

optional arguments:

-h: Display help message

--include-merged: include merged PRs in analysis

--dry-run: Show what would be done, without making any changes

About

Captures and stores data about a GitHub repo for archival purposes

Topics

Resources

 Readme

License

 MIT license

Code of conduct

 Code of conduct

Stars

 0 stars

Watchers

 0 watching

Forks

 2 forks

Releases

 1 tags

Create a new release

Packages

No packages published

Publish your first package

Languages

Python

50.0%

 

JavaScript

39.9%

 

HTML

6.6%

 

Gherkin

2.4%

 

Makefile

1.1%

Footer

© 2023 GitHub, Inc.

Footer navigation

Terms

Privacy

Security

Status

Docs

Contact GitHub

Pricing

API

Training

Blog

About

mowjoejoejoejoe/archive-repo at patch-1
